### ISSUE TITLE
Please include hacktober tag and label

### ISSUE THREAD

**Issue by debasish212** [LuanDevecchi/HacktoberfestAlgo2019#150]
Sir , please include the Hacktober feast tag and label .or we will not be considered as participants. So sir please do it asap. And sir also include contribute.md file 

They say:)
Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest.
Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by LuanDevecchi** [comment]
There is, already.
![image](https://user-images.githubusercontent.com/27377250/95021471-94926980-0647-11eb-87be-a1d399dcd078.png)
